### PR TITLE
Resolved legacy registry error by pointing to official jenkins image

### PR DESCRIPTION
**Pull request by modulusx**
Hi Viktor,

Awesome job on the docker-swarm tutorial. I'm pretty new to containers and your blog posts are super helpful.  On docker-swarm, during vagrant up, I got "docker.io/vfarcic/jenkins: this image was pulled from a legacy registry." and was able to fix it by switching it to the official image.  I don't know how different your image is, but this allowed me to continue your tutorial through the end of Part 1/4.  Hope this helps.

### CODE REVIEW

**Comment by vfarcic** [comment]
You're right. The Jenkins I created should be deprecated. I built it at the time there was no official Jenkins container. Can you please let me know the URL of the article that uses this code so that I make changes to the text as well?

**Comment by modulusx** [comment]
Its not in the text of Scaling to Infinity, but it is in the text of Continuous Integration, Delivery, or Deployment: http://technologyconversations.com/2015/02/11/continuous-integration-delivery-or-deployment-with-jenkins-docker-and-ansible/

**Comment by huygn** [comment]
I bumped on this today, please consider merge this PR so ppl like me wont panic.

**Comment by huygn** [comment]
thanks @vfarcic for merged the other PR too, and awsome articles btw!

**Pull request merged**
